version: '3'
services:
   lb:
    build:
      context: ./lb
      dockerfile: dockerfile_lb_nginx
    #volumes:
     # - "./web/src:/web/src"
    ports:
      - "88:80"
   apl1:
    build:
      context: ./apl
      dockerfile: dockerfile_apl
    #volumes:
     # - "./web/src:/web/src"
    ports:
      - "8081:8080"
   apl2:
    build:
      context: ./apl
      dockerfile: dockerfile_apl
    #volumes:
     # - "./web/src:/web/src"
    ports:
      - "8083:8080" 
   db:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    #volumes:
     # - "./web/src:/web/src"
    ports:
      - "3306:3306"